# Configure main menu and social menu
[[main]]
identifier = "book"
name = "Eldiron Book"
url = "https://book.eldiron.com"
[main.params]
icon = "book"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/markusmoenig/Eldiron"

[social.params]
icon = "brand-github"

[[social]]
identifier = "patreon"
name = "Patreon"
url = "https://patreon.com/eldiron"

[social.params]
icon = "brand-patreon"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/EldironRPG"

[social.params]
icon = "brand-twitter"

# [[social]]
# identifier = "book"
# name = "Book"
# url = "https://book.eldiron.com"

# [social.params]
# icon = "book"
